export const DEVICE_MICROSERVICE = 'DEVICE_MICROSERVICE';
export const MQTT_BROKER = 'MQTT_BROKER';
export const USER_AUTH_MICROSERVICE = 'USER_AUTH_MICROSERVICE';
export const API_GATEWAY = 'API_GATEWAY';
